### ISSUE TITLE
fix merge conflicts

### ISSUE THREAD

**Issue by aric87** [bpcoxjr/flappy-bird-main#21]
https://github.com/bpcoxjr/flappy-bird-main/blob/master/site/index.html#L153
https://github.com/bpcoxjr/flappy-bird-main/blob/master/site/js/settings.js#L4
https://github.com/bpcoxjr/flappy-bird-main/blob/master/site/js/app.js#L1
https://github.com/bpcoxjr/flappy-bird-main/blob/master/site/js/systems/input.js#L5
https://github.com/bpcoxjr/flappy-bird-main/blob/master/site/js/systems/graphics.js#L165
https://github.com/bpcoxjr/flappy-bird-main/blob/master/site/css/styles.css#L40

**Comment by bpcoxjr** [comment]
Fixed.
